# Generated by Django 4.2.7 on 2025-10-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_service', '0001_initial'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='blogs.blog'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['blog', 'status'], name='ai_service__blog_id_154a57_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['status', '-created_at'], name='ai_service__status_c73ae9_idx'),
        ),
    ]
